/*
||MongoDB 
MongoDB is a NoSQL database ie. it has collections and documents.

*Collection
    A collection has many documents
    In our case we will have a blog collection

*Documents
    A document represents a single piece of data
    In our case the document will have the blog title, snippet and the body
||Mongoose
    Once the cluster has been created in the mogoDB Atlas(website) we need to connect using to the DB. MongoDB provides us with an API but it is verbose so we use mongoose
    Mongoose is an ODM library(Object Document Mapping) => means it wraps the mongoDB api and provides us a much easier way to connect to our DB

||Schemas
    Schemas define the structure of the document stored in the collection
    Eg: User schema
        name(string), required
        age(number)
        bio(string), required
        The ID will be autogenerated 

||Models
    Models allow us to communicate with the database collection
*/

